### ISSUE TITLE
webmention json sharding

### ISSUE THREAD

**Issue by tomasparks** [vipickering/vincentp#108]
Have you looked at splitting up the webmention json file like this:

> ├── _data
> |   └── comments
> |      └── 365-days-of-drawing
> |      |   └── comment-2013-08-30-162902.yml
> |      |   └── comment-2013-08-30-204505.yml
> |      └── basics
> |         └── comment-2014-02-10-040840.ym

PS: sorry my website's note system is down

**Comment by vipickering** [comment]
Oh thanks! Cool idea.

It might suffer from the same problem I currently have; Which is looping through such a large file to parse it for each page.

I'll run some tests when I get a chance to see if it improves performance.
