### ISSUE TITLE
Collate collections by tag, rather than by globbing folders

### ISSUE THREAD

**Issue by paulrobertlloyd** [vipickering/vincentp#134]
Congrats on moving to Jekyll! Nice to have speedy builds, isn’t it 😃 Anyway, was just being nosey, and noticed you are creating collections by globbing files, i.e.:

```
module.exports = (function (collection) {
    return collection.getFilteredByGlob([
        "src/_content/notes/*.md"
    ]);
});
```

Another way to achieve this is by adding default tags within your folder data files. So, for example in `/src/_content/notes/notes.json`, you could add:

```
{
  "layout": "notes",
  "category": "Notes",
  "twitterCard": false,
  "permalink": "/notes/{{date | date: '%Y/%m/%d/%H-%M'}}/index.html",
  "tags": ["notes"]
}
```

I’ve found this to be marginally faster too, but YMMV. (Not sure what `category` is used for, but you may be able to combine these two values, also).

**Comment by vipickering** [comment]
Thanks always welcome input :-)

I am planning on adding tags etc to the pages once I do the redesign (some things will move so its a good opportunity), I got lazy and didn't fancy manually adding it on to every page in the meantime!

I have noticed that basically anything in the templating area seems to be slower than doing it in JavaScript so I have plans to streamline alot of this code once I do the next phase. Especially around processing webmentions where I was previously doing a lot of heavy templating things.
